write-the-docs-quorum/quorum-meetups

README.md

This PR adds some content to the README explaining the Quorum program and how to participate.

Add initial content to the README

---

README.md

Removing the TOC since it doesn't work

Remove TOC

---

meetup-logistics/decision-log.md

This PR adds a decision log for tracking important quorum decisions.

Add decision log

---

README.md
decision-log.md

This MR updates the README to include a link to our new mailing list on groups.io. It also updates the decision log.

Add mailing list to decision log and README

---

README.md
decision-log.md

This PR defines the quarters for our group and adds our meetup schedule to the README.

Add meetup schedule and quarter definition

---

README.md
decision-log.md
emcee-script.md
meeting-agenda-detailed.md

This PR:
- Adds the meeting agenda to the README
- Adds the decision we made about the meeting agenda to the decision log
- Creates a new file that includes a detailed breakdown of the meeting agenda
- Creates a new file that includes an adaptation of the WTD Bay Area emcee script

Add meeting agenda and supporting documents

---

README.md
decision-log.md

This PR adds:
- Details about the West Coast meetup
- Links to both meetups
- Calendars for East and West Coast events
It also updates the decision log to reflect these changes.

Add Meetup details and supporting documents

---

README.md

This MR fixes a few minor phrasing and style issues and adds clarification about meeting times.

Add meeting times

---

README.md
meeting-agenda-detailed.md

This PR adds instructions for how to handle breakout rooms and lists a new participating meetup.

Add breakout room info and new participating meetup

---

README.md
decision-log.md
meetup-publicity-detailed.md
meetup-schedule-detailed.md

This MR simplifies the README, adds some additional content, and creates two new documents to explain the newly decided policies around meeting schedules and publicity.

Update schedules and publicity policies

---

README.md
meetup-organizing.md
zoom-coordinator-guide.md

This PR adds a link to the new organizing guide from the README and experiments with line endings that use a single line for each sentence with soft wraps.

Add link to organizing guide from README and fix line endings

---

README.md
zoom-coordinator-guide.md

Creates new guide for Zoom coordinators

Add Zoom coordinator guide

---

README.md
zoom-coordinator-guide.md

Fix typos and add a clarifying sentence.

Fix typos and add a clarifying sentence

---

zoom-coordinator-guide.md

This will remove merge conflict artifacts.

Remove merge conflict artifacts

---

README.md

Adding some emoji to the README to give it some flair and panache.

Add emoji to README for flair

---

zoom-coordinator-guide.md

I'm adding a note about the meeting being recorded and Zoom caps to the meetup event template.

Update Meetup event description template

---

README.md
zoom-coordinator-guide.md

Adds the Washington DC meetup to the README and Zoom Coordinator Guide.

Add Washington DC meetup

---

README.md
zoom-coordinator-guide.md

This PR adds the Seattle meetup to the list of West Coast Quorum participants.

Add Seattle to West Coast Quorum

---

zoom-coordinator-guide.md

This PR adds Australia to Zoom coordinator guide.

Add Australia to Zoom coordinator guide

---

meetup-roles.md

Capturing some ideas for meetup roles.

Initial draft of meetup roles doc

---

README.md
zoom-coordinator-guide.md

SLC is no longer participating in West Coast, so I'm removing that meetup.

Remove SLC from participating meetups

---

meetup-schedule-detailed.md
past-quorum-meetups.md

This PR adds the 2022 schedule and creates a new page with details of past events.

Add 2022 schedule and archive of past events

---

zoom-coordinator-guide.md

This is a minor PR that updates the reference to which YouTube channels the videos will be posted to.

Minor text updates to YouTube references

---

README.md
zoom-coordinator-guide.md

Adds Toronto, CA to the list of participating meetups.

Add Toronto to the participating meetups

---

past-quorum-meetups.md

This PR adds the information about the January 2022 West Coast/Australia meetup.

Add Jan 2022 meetup details

---

past-quorum-meetups.md

This PR adds the details about the Feb 2022 East Coast Quorum meetup.

Add Feb 2022 meetup details

---

running-a-tech-check.md

This PR adds security measures to the list of things to cover during a tech check.

Add security measures to tech check

---

running-a-tech-check.md

This PR fixes some minor formatting and phrasing errors in the new security measures on the tech check guide.

Fix errors in new security measures

---

past-quorum-meetups.md
running-a-tech-check.md

This PR adds the details for the recent West Coast Quorum event.

Update past Quorum events

---

past-quorum-meetups.md

Adding date to past Quorum events.

Add date to April 2022 event

---

README.md
meeting-agenda-detailed.md
past-quorum-meetups.md
zoom-coordinator-guide.md

This PR updates various files to reflect recent changes and create the calendar for 2023.

Various updates for the Autumn

---

past-quorum-meetups.md

This PR adds the September quorum information.

Add Sept quorum details
